apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "photoprism.fullname" . }}-photos
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.photos.size }}
  storageClassName: {{ .Values.persistence.photos.storageClass | quote }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "photoprism.fullname" . }}-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.storage.size }}
  storageClassName: {{ .Values.persistence.storage.storageClass | quote }} 